{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spring-boot-web-chart.serviceAccountName" . }}
  labels:
{{ include "spring-boot-web-chart.labels" . | nindent 4 }}
{{- end -}}
